### ISSUE TITLE
Add code hints?

### ISSUE THREAD

**Issue by thany** [peterflynn/svg-preview#10] opened 2014-06-19 11:39 UTC
Would it be possible to have this extension also add code hints for SVG files, andpossibly for tags within `<svg>` within rwgular html?

**Comment by peterflynn** [comment] 2015-03-10 04:26
Closing since code hints for SVG are now a core Brackets feature. They don't have all the fancy context-awareness you suggested, but I think the right place for those improvements would be in Brackets itself rather than here.

**Closed by peterflynn** 2015-03-10 04:26 UTC

**Comment by thany** [comment] 2015-03-13 13:42
Well, maybe in Brackets 1.2... But 1.2 has a [huge bug](https://github.com/adobe/brackets/issues/6684) that keeps many users from using it.

**Comment by peterflynn** [comment] 2015-03-13 22:59
@thany That bug was present in 1.1 also and it didn't stop a few hundred thousand people from updating :-)

At any rate, that doesn't justify building a complete duplicate of that functionality in this extension.  If you really want, it'd be far less work to download the Brackets source and run the 1.2 JS code in the 1.0 native shell.
